-- MySQL Script generated by MySQL Workbench
-- Fri Mar  1 13:24:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrainerConnect
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TrainerConnect` ;

-- -----------------------------------------------------
-- Schema TrainerConnect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainerConnect` DEFAULT CHARACTER SET utf8 ;
USE `TrainerConnect` ;

-- -----------------------------------------------------
-- Table `TrainerConnect`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainerConnect`.`Client` ;

CREATE TABLE IF NOT EXISTS `TrainerConnect`.`Client` (
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(2) NULL,
  `email` VARCHAR(254) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  `id` INT NOT NULL,
  `weight` DECIMAL NULL,
  `height` DECIMAL NULL,
  `trainer_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainerConnect`.`Trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainerConnect`.`Trainer` ;

CREATE TABLE IF NOT EXISTS `TrainerConnect`.`Trainer` (
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(2) NULL,
  `email` VARCHAR(254) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  `id` INT NOT NULL,
  `client_count` INT NOT NULL,
  `client_limit` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TrainerConnect`.`Client`
-- -----------------------------------------------------
START TRANSACTION;
USE `TrainerConnect`;
INSERT INTO `TrainerConnect`.`Client` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `weight`, `height`, `trainer_id`) VALUES ('Erwin', 'B.', 19, 'M', 'erwin@cartaroom.com', 'February 5, 2019', 85, NULL, NULL, 7);
INSERT INTO `TrainerConnect`.`Client` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `weight`, `height`, `trainer_id`) VALUES ('Antonio', 'C.', 18, 'M', 'erwin@cartaroom.com', 'February 5, 2019', 90, NULL, NULL, 1);
INSERT INTO `TrainerConnect`.`Client` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `weight`, `height`, `trainer_id`) VALUES ('Carlo', 'M.', NULL, 'M', 'carlo@tracesocialmedia.com', 'February 5, 2019', 95, NULL, NULL, 23);
INSERT INTO `TrainerConnect`.`Client` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `weight`, `height`, `trainer_id`) VALUES ('Toni', 'H.', NULL, 'F', 'toni@tracesocialmedia.com', 'February 5, 2019', 107, NULL, NULL, 58);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TrainerConnect`.`Trainer`
-- -----------------------------------------------------
START TRANSACTION;
USE `TrainerConnect`;
INSERT INTO `TrainerConnect`.`Trainer` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `client_count`, `client_limit`) VALUES ('William', 'Bradshaw', 19, 'M', 'william@trainerconnect.com', 'January 12, 2019', 7, 1, 10);
INSERT INTO `TrainerConnect`.`Trainer` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `client_count`, `client_limit`) VALUES ('Jeffrey', 'Stephen', 19, 'M', 'jeff@trainerconnect.com', 'January 19, 2019', 23, 2, 20);
INSERT INTO `TrainerConnect`.`Trainer` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `client_count`, `client_limit`) VALUES ('Jinwoo', 'Kim', NULL, 'M', 'jin@trainerconnect.com', 'March 1, 2019', 58, 0, 5);
INSERT INTO `TrainerConnect`.`Trainer` (`first_name`, `last_name`, `age`, `gender`, `email`, `date_joined`, `id`, `client_count`, `client_limit`) VALUES ('Keith', 'Liu', NULL, 'M', 'keith@trainerconnect.com', 'December 11, 2018', 1, 1, 20);

COMMIT;

